/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserAccessEntry = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const DocumentRecord = IDL.Record({
  'id' : IDL.Text,
  'ownerName' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'filePath' : IDL.Text,
  'fileSize' : IDL.Nat,
  'parentFolderId' : IDL.Opt(IDL.Text),
  'isPublic' : IDL.Bool,
  'uploadedAt' : IDL.Int,
});
export const Holiday = IDL.Variant({
  'newyear' : IDL.Null,
  'none' : IDL.Null,
  'easter' : IDL.Null,
  'midsommar' : IDL.Null,
  'christmas' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const UserAccessLogEntry = IDL.Record({
  'id' : IDL.Text,
  'metadata' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ContactStatus = IDL.Variant({
  'active' : IDL.Null,
  'notactive' : IDL.Null,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : ContactStatus,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'senderBlocked' : IDL.Bool,
  'senderPrincipal' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'deviceId' : IDL.Opt(IDL.Text),
});
export const FolderRecord = IDL.Record({
  'id' : IDL.Text,
  'ownerName' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'parentFolderId' : IDL.Opt(IDL.Text),
});
export const NoteRecord = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'rubrik' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'sharedWith' : IDL.Vec(IDL.Principal),
});
export const UserListEntry = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});

export const idlService = IDL.Service({
  'addUser' : IDL.Func(
      [IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'admin_addUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
  'admin_getUserAccess' : IDL.Func([], [IDL.Vec(UserAccessEntry)], ['query']),
  'admin_updateUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
  'blockContactSender' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'blockUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'bulkMove' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'clearUserAccessLog' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createFolder' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createNote' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteContactMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteContactMessages' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteDocument' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteFolder' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteNote' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUserAccessLogEntries' : IDL.Func(
      [IDL.Principal, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'finalizeChunkedUpload' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DocumentRecord, 'err' : IDL.Text })],
      [],
    ),
  'getActiveHoliday' : IDL.Func([], [Holiday], ['query']),
  'getBlockedSenders' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'getDocumentChunk' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'hasMore' : IDL.Bool,
            'chunk' : IDL.Vec(IDL.Nat8),
            'totalSize' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getDocumentData' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'data' : IDL.Vec(IDL.Nat8),
            'mimeType' : IDL.Text,
            'fileName' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getGuestDocumentUploadPermission' : IDL.Func([], [IDL.Bool], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getMyStorageUsed' : IDL.Func([], [IDL.Nat], ['query']),
  'getNoteShares' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Principal), 'err' : IDL.Text })],
      ['query'],
    ),
  'getNotesCount' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'getUserAccessLog' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Vec(UserAccessLogEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'listContactMessages' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ContactMessage), 'err' : IDL.Text })],
      [],
    ),
  'listMyDocuments' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'listMyFolders' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(FolderRecord)],
      ['query'],
    ),
  'listNotes' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Vec(NoteRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'listPublicDocuments' : IDL.Func([], [IDL.Vec(DocumentRecord)], ['query']),
  'listUsers' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(UserListEntry), 'err' : IDL.Text })],
      [],
    ),
  'moveDocument' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'moveFolder' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'recordMyAccess' : IDL.Func([IDL.Text], [], []),
  'removeUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setActiveHoliday' : IDL.Func(
      [Holiday],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setDocumentPublic' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setGuestDocumentUploadPermission' : IDL.Func(
      [IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'shareNote' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'startChunkedUpload' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'unblockContactSender' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unshareNote' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateContactStatus' : IDL.Func(
      [IDL.Text, ContactStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateUserRole' : IDL.Func(
      [IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'uploadDocumentChunk' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'uploadDocumentWithData' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : DocumentRecord, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserAccessEntry = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const DocumentRecord = IDL.Record({
    'id' : IDL.Text,
    'ownerName' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'filePath' : IDL.Text,
    'fileSize' : IDL.Nat,
    'parentFolderId' : IDL.Opt(IDL.Text),
    'isPublic' : IDL.Bool,
    'uploadedAt' : IDL.Int,
  });
  const Holiday = IDL.Variant({
    'newyear' : IDL.Null,
    'none' : IDL.Null,
    'easter' : IDL.Null,
    'midsommar' : IDL.Null,
    'christmas' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const UserAccessLogEntry = IDL.Record({
    'id' : IDL.Text,
    'metadata' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ContactStatus = IDL.Variant({
    'active' : IDL.Null,
    'notactive' : IDL.Null,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : ContactStatus,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'senderBlocked' : IDL.Bool,
    'senderPrincipal' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'deviceId' : IDL.Opt(IDL.Text),
  });
  const FolderRecord = IDL.Record({
    'id' : IDL.Text,
    'ownerName' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'parentFolderId' : IDL.Opt(IDL.Text),
  });
  const NoteRecord = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'rubrik' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'sharedWith' : IDL.Vec(IDL.Principal),
  });
  const UserListEntry = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  
  return IDL.Service({
    'addUser' : IDL.Func(
        [IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'admin_addUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
    'admin_getUserAccess' : IDL.Func([], [IDL.Vec(UserAccessEntry)], ['query']),
    'admin_updateUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
    'blockContactSender' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'blockUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'bulkMove' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'clearUserAccessLog' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createFolder' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteContactMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteContactMessages' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteDocument' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteFolder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteNote' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUserAccessLogEntries' : IDL.Func(
        [IDL.Principal, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'finalizeChunkedUpload' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DocumentRecord, 'err' : IDL.Text })],
        [],
      ),
    'getActiveHoliday' : IDL.Func([], [Holiday], ['query']),
    'getBlockedSenders' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'getDocumentChunk' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'hasMore' : IDL.Bool,
              'chunk' : IDL.Vec(IDL.Nat8),
              'totalSize' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getDocumentData' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'data' : IDL.Vec(IDL.Nat8),
              'mimeType' : IDL.Text,
              'fileName' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getGuestDocumentUploadPermission' : IDL.Func([], [IDL.Bool], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getMyStorageUsed' : IDL.Func([], [IDL.Nat], ['query']),
    'getNoteShares' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Principal), 'err' : IDL.Text })],
        ['query'],
      ),
    'getNotesCount' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'getUserAccessLog' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Vec(UserAccessLogEntry), 'err' : IDL.Text })],
        ['query'],
      ),
    'listContactMessages' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ContactMessage), 'err' : IDL.Text })],
        [],
      ),
    'listMyDocuments' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'listMyFolders' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(FolderRecord)],
        ['query'],
      ),
    'listNotes' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Vec(NoteRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'listPublicDocuments' : IDL.Func([], [IDL.Vec(DocumentRecord)], ['query']),
    'listUsers' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(UserListEntry), 'err' : IDL.Text })],
        [],
      ),
    'moveDocument' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'moveFolder' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'recordMyAccess' : IDL.Func([IDL.Text], [], []),
    'removeUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setActiveHoliday' : IDL.Func(
        [Holiday],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setDocumentPublic' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setGuestDocumentUploadPermission' : IDL.Func(
        [IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'shareNote' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'startChunkedUpload' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'unblockContactSender' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unshareNote' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateContactStatus' : IDL.Func(
        [IDL.Text, ContactStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateUserRole' : IDL.Func(
        [IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'uploadDocumentChunk' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'uploadDocumentWithData' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : DocumentRecord, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };