/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserAccessEntry = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const Holiday = IDL.Variant({
  'newyear' : IDL.Null,
  'none' : IDL.Null,
  'easter' : IDL.Null,
  'midsommar' : IDL.Null,
  'christmas' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const ContactStatus = IDL.Variant({
  'active' : IDL.Null,
  'notactive' : IDL.Null,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : ContactStatus,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'senderBlocked' : IDL.Bool,
  'senderPrincipal' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'deviceId' : IDL.Opt(IDL.Text),
});
export const UserListEntry = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});

export const idlService = IDL.Service({
  'addUser' : IDL.Func(
      [IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'admin_addUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
  'admin_getUserAccess' : IDL.Func([], [IDL.Vec(UserAccessEntry)], ['query']),
  'admin_updateUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
  'blockContactSender' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'blockUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteContactMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteContactMessages' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveHoliday' : IDL.Func([], [Holiday], ['query']),
  'getBlockedSenders' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'listContactMessages' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ContactMessage), 'err' : IDL.Text })],
      [],
    ),
  'listUsers' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(UserListEntry), 'err' : IDL.Text })],
      [],
    ),
  'removeUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setActiveHoliday' : IDL.Func(
      [Holiday],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'unblockContactSender' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateContactStatus' : IDL.Func(
      [IDL.Text, ContactStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateUserRole' : IDL.Func(
      [IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserAccessEntry = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const Holiday = IDL.Variant({
    'newyear' : IDL.Null,
    'none' : IDL.Null,
    'easter' : IDL.Null,
    'midsommar' : IDL.Null,
    'christmas' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const ContactStatus = IDL.Variant({
    'active' : IDL.Null,
    'notactive' : IDL.Null,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : ContactStatus,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'senderBlocked' : IDL.Bool,
    'senderPrincipal' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'deviceId' : IDL.Opt(IDL.Text),
  });
  const UserListEntry = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  
  return IDL.Service({
    'addUser' : IDL.Func(
        [IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'admin_addUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
    'admin_getUserAccess' : IDL.Func([], [IDL.Vec(UserAccessEntry)], ['query']),
    'admin_updateUserAccess' : IDL.Func([IDL.Text, UserRole], [], []),
    'blockContactSender' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'blockUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteContactMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteContactMessages' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveHoliday' : IDL.Func([], [Holiday], ['query']),
    'getBlockedSenders' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'listContactMessages' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ContactMessage), 'err' : IDL.Text })],
        [],
      ),
    'listUsers' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(UserListEntry), 'err' : IDL.Text })],
        [],
      ),
    'removeUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setActiveHoliday' : IDL.Func(
        [Holiday],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'unblockContactSender' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateContactStatus' : IDL.Func(
        [IDL.Text, ContactStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateUserRole' : IDL.Func(
        [IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };