/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : string,
  'status' : ContactStatus,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'senderBlocked' : boolean,
  'senderPrincipal' : [] | [string],
  'message' : string,
  'deviceId' : [] | [string],
}
export type ContactStatus = { 'active' : null } |
  { 'notactive' : null };
export interface DocumentRecord {
  'id' : string,
  'ownerName' : string,
  'ownerPrincipal' : Principal,
  'mimeType' : string,
  'fileName' : string,
  'filePath' : string,
  'fileSize' : bigint,
  'parentFolderId' : [] | [string],
  'isPublic' : boolean,
  'uploadedAt' : bigint,
}
export interface FolderRecord {
  'id' : string,
  'ownerName' : string,
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'parentFolderId' : [] | [string],
}
export type Holiday = { 'newyear' : null } |
  { 'none' : null } |
  { 'easter' : null } |
  { 'midsommar' : null } |
  { 'christmas' : null };
export interface UserAccessEntry { 'principal' : Principal, 'role' : UserRole }
export interface UserAccessLogEntry {
  'id' : string,
  'metadata' : string,
  'timestamp' : bigint,
}
export interface UserListEntry {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
  'registeredAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addUser' : ActorMethod<
    [string, UserRole],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'admin_addUserAccess' : ActorMethod<[string, UserRole], undefined>,
  'admin_getUserAccess' : ActorMethod<[], Array<UserAccessEntry>>,
  'admin_updateUserAccess' : ActorMethod<[string, UserRole], undefined>,
  'blockContactSender' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'blockUser' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'bulkMove' : ActorMethod<
    [Array<string>, Array<string>, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'clearUserAccessLog' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createFolder' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteContactMessage' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteContactMessages' : ActorMethod<
    [Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteDocument' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteFolder' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteUserAccessLogEntries' : ActorMethod<
    [Principal, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'finalizeChunkedUpload' : ActorMethod<
    [string],
    { 'ok' : DocumentRecord } |
      { 'err' : string }
  >,
  'getActiveHoliday' : ActorMethod<[], Holiday>,
  'getBlockedSenders' : ActorMethod<
    [],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'getDocumentData' : ActorMethod<
    [string],
    {
        'ok' : { 'data' : Uint8Array, 'mimeType' : string, 'fileName' : string }
      } |
      { 'err' : string }
  >,
  'getGuestDocumentUploadPermission' : ActorMethod<[], boolean>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getMyStorageUsed' : ActorMethod<[], bigint>,
  'getUserAccessLog' : ActorMethod<
    [Principal],
    { 'ok' : Array<UserAccessLogEntry> } |
      { 'err' : string }
  >,
  'listContactMessages' : ActorMethod<
    [],
    { 'ok' : Array<ContactMessage> } |
      { 'err' : string }
  >,
  'listMyDocuments' : ActorMethod<[[] | [string]], Array<DocumentRecord>>,
  'listMyFolders' : ActorMethod<[[] | [string]], Array<FolderRecord>>,
  'listPublicDocuments' : ActorMethod<[], Array<DocumentRecord>>,
  'listUsers' : ActorMethod<
    [],
    { 'ok' : Array<UserListEntry> } |
      { 'err' : string }
  >,
  'moveDocument' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'moveFolder' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'recordMyAccess' : ActorMethod<[string], undefined>,
  'removeUser' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'setActiveHoliday' : ActorMethod<
    [Holiday],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDocumentPublic' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setGuestDocumentUploadPermission' : ActorMethod<
    [boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'startChunkedUpload' : ActorMethod<
    [string, string, string, boolean, [] | [string], bigint, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitContact' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'unblockContactSender' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateContactStatus' : ActorMethod<
    [string, ContactStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateUserProfile' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateUserRole' : ActorMethod<
    [string, UserRole],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadDocument' : ActorMethod<
    [string, string, string, boolean, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'uploadDocumentChunk' : ActorMethod<
    [string, bigint, Uint8Array],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'uploadDocumentWithData' : ActorMethod<
    [string, Uint8Array, string, boolean, [] | [string]],
    { 'ok' : DocumentRecord } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];