/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserAccessEntry {
    principal: Principal;
    role: UserRole;
}
export interface DocumentRecord {
    id: string;
    ownerName: string;
    ownerPrincipal: Principal;
    mimeType: string;
    fileName: string;
    filePath: string;
    fileSize: bigint;
    parentFolderId?: string;
    isPublic: boolean;
    uploadedAt: bigint;
}
export interface ContactMessage {
    id: string;
    status: ContactStatus;
    name: string;
    submittedAt: bigint;
    email: string;
    senderBlocked: boolean;
    senderPrincipal?: string;
    message: string;
    deviceId?: string;
}
export interface UserAccessLogEntry {
    id: string;
    metadata: string;
    timestamp: bigint;
}
export interface UserListEntry {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
    registeredAt: bigint;
}
export interface FolderRecord {
    id: string;
    ownerName: string;
    ownerPrincipal: Principal;
    name: string;
    createdAt: bigint;
    parentFolderId?: string;
}
export enum ContactStatus {
    active = "active",
    notactive = "notactive"
}
export enum Holiday {
    newyear = "newyear",
    none = "none",
    easter = "easter",
    midsommar = "midsommar",
    christmas = "christmas"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addUser(principalText: string, role: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    admin_addUserAccess(userPrincipalText: string, role: UserRole): Promise<void>;
    admin_getUserAccess(): Promise<Array<UserAccessEntry>>;
    admin_updateUserAccess(userPrincipalText: string, newRole: UserRole): Promise<void>;
    blockContactSender(principalText: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    blockUser(principalText: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    bulkMove(docIds: Array<string>, folderIds: Array<string>, targetFolderId: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    clearUserAccessLog(target: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createFolder(name: string, parentFolderId: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteContactMessage(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteContactMessages(ids: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteDocument(documentId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteFolder(folderId: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteUserAccessLogEntries(target: Principal, entryIds: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    finalizeChunkedUpload(sessionId: string): Promise<{
        __kind__: "ok";
        ok: DocumentRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveHoliday(): Promise<Holiday>;
    getBlockedSenders(): Promise<{
        __kind__: "ok";
        ok: Array<string>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getDocumentData(docId: string): Promise<{
        __kind__: "ok";
        ok: {
            data: Uint8Array;
            mimeType: string;
            fileName: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    getGuestDocumentUploadPermission(): Promise<boolean>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyRole(): Promise<UserRole>;
    getMyStorageUsed(): Promise<bigint>;
    getUserAccessLog(target: Principal): Promise<{
        __kind__: "ok";
        ok: Array<UserAccessLogEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listContactMessages(): Promise<{
        __kind__: "ok";
        ok: Array<ContactMessage>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listMyDocuments(parentFolderId: string | null): Promise<Array<DocumentRecord>>;
    listMyFolders(parentFolderId: string | null): Promise<Array<FolderRecord>>;
    listPublicDocuments(): Promise<Array<DocumentRecord>>;
    listUsers(): Promise<{
        __kind__: "ok";
        ok: Array<UserListEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    moveDocument(docId: string, targetFolderId: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    moveFolder(folderId: string, targetFolderId: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordMyAccess(metadata: string): Promise<void>;
    removeUser(principalText: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setActiveHoliday(holiday: Holiday): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setDocumentPublic(documentId: string, isPublic: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setGuestDocumentUploadPermission(allowed: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    startChunkedUpload(sessionId: string, fileName: string, mimeType: string, isPublic: boolean, parentFolderId: string | null, totalChunks: bigint, totalFileSize: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitContact(name: string, email: string, message: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unblockContactSender(principalText: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateContactStatus(id: string, status: ContactStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateMyProfile(name: string, email: string, phone: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateUserProfile(principalText: string, name: string, email: string, phone: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateUserRole(principalText: string, newRole: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    uploadDocument(fileName: string, filePath: string, mimeType: string, isPublic: boolean, fileSize: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    uploadDocumentChunk(sessionId: string, chunkIndex: bigint, chunkData: Uint8Array): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    uploadDocumentWithData(fileName: string, fileData: Uint8Array, mimeType: string, isPublic: boolean, parentFolderId: string | null): Promise<{
        __kind__: "ok";
        ok: DocumentRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ContactMessage as _ContactMessage, ContactStatus as _ContactStatus, DocumentRecord as _DocumentRecord, FolderRecord as _FolderRecord, Holiday as _Holiday, UserAccessEntry as _UserAccessEntry, UserAccessLogEntry as _UserAccessLogEntry, UserListEntry as _UserListEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addUser(arg0: string, arg1: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_addUserAccess(arg0: string, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_addUserAccess(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_addUserAccess(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async admin_getUserAccess(): Promise<Array<UserAccessEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_getUserAccess();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_getUserAccess();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_updateUserAccess(arg0: string, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_updateUserAccess(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_updateUserAccess(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockContactSender(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.blockContactSender(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockContactSender(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async blockUser(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkMove(arg0: Array<string>, arg1: Array<string>, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkMove(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkMove(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearUserAccessLog(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.clearUserAccessLog(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearUserAccessLog(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFolder(arg0: string, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContactMessage(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactMessage(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactMessage(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContactMessages(arg0: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactMessages(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactMessages(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDocument(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFolder(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUserAccessLogEntries(arg0: Principal, arg1: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserAccessLogEntries(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserAccessLogEntries(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async finalizeChunkedUpload(arg0: string): Promise<{
        __kind__: "ok";
        ok: DocumentRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeChunkedUpload(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeChunkedUpload(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveHoliday(): Promise<Holiday> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveHoliday();
                return from_candid_Holiday_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveHoliday();
            return from_candid_Holiday_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedSenders(): Promise<{
        __kind__: "ok";
        ok: Array<string>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedSenders();
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedSenders();
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentData(arg0: string): Promise<{
        __kind__: "ok";
        ok: {
            data: Uint8Array;
            mimeType: string;
            fileName: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentData(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentData(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuestDocumentUploadPermission(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuestDocumentUploadPermission();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuestDocumentUploadPermission();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStorageUsed(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStorageUsed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStorageUsed();
            return result;
        }
    }
    async getUserAccessLog(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: Array<UserAccessLogEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccessLog(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccessLog(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContactMessages(): Promise<{
        __kind__: "ok";
        ok: Array<ContactMessage>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactMessages();
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactMessages();
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyDocuments(arg0: string | null): Promise<Array<DocumentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyDocuments(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyDocuments(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyFolders(arg0: string | null): Promise<Array<FolderRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyFolders(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyFolders(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublicDocuments(): Promise<Array<DocumentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublicDocuments();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublicDocuments();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<{
        __kind__: "ok";
        ok: Array<UserListEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async moveDocument(arg0: string, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.moveDocument(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveDocument(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async moveFolder(arg0: string, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.moveFolder(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveFolder(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordMyAccess(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMyAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMyAccess(arg0);
            return result;
        }
    }
    async removeUser(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setActiveHoliday(arg0: Holiday): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveHoliday(to_candid_Holiday_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveHoliday(to_candid_Holiday_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDocumentPublic(arg0: string, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setDocumentPublic(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDocumentPublic(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGuestDocumentUploadPermission(arg0: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setGuestDocumentUploadPermission(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGuestDocumentUploadPermission(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async startChunkedUpload(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: string | null, arg5: bigint, arg6: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.startChunkedUpload(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startChunkedUpload(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async unblockContactSender(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockContactSender(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockContactSender(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContactStatus(arg0: string, arg1: ContactStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactStatus(arg0, to_candid_ContactStatus_n37(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactStatus(arg0, to_candid_ContactStatus_n37(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: string, arg1: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadDocument(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadDocumentChunk(arg0: string, arg1: bigint, arg2: Uint8Array): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocumentChunk(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocumentChunk(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadDocumentWithData(arg0: string, arg1: Uint8Array, arg2: string, arg3: boolean, arg4: string | null): Promise<{
        __kind__: "ok";
        ok: DocumentRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocumentWithData(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocumentWithData(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContactMessage_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactMessage): ContactMessage {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ContactStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactStatus): ContactStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentRecord_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentRecord): DocumentRecord {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FolderRecord_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FolderRecord): FolderRecord {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Holiday_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Holiday): Holiday {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccessEntry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccessEntry): UserAccessEntry {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserListEntry_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserListEntry): UserListEntry {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ownerName: string;
    ownerPrincipal: Principal;
    mimeType: string;
    fileName: string;
    filePath: string;
    fileSize: bigint;
    parentFolderId: [] | [string];
    isPublic: boolean;
    uploadedAt: bigint;
}): {
    id: string;
    ownerName: string;
    ownerPrincipal: Principal;
    mimeType: string;
    fileName: string;
    filePath: string;
    fileSize: bigint;
    parentFolderId?: string;
    isPublic: boolean;
    uploadedAt: bigint;
} {
    return {
        id: value.id,
        ownerName: value.ownerName,
        ownerPrincipal: value.ownerPrincipal,
        mimeType: value.mimeType,
        fileName: value.fileName,
        filePath: value.filePath,
        fileSize: value.fileSize,
        parentFolderId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.parentFolderId)),
        isPublic: value.isPublic,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ContactStatus;
    name: string;
    submittedAt: bigint;
    email: string;
    senderBlocked: boolean;
    senderPrincipal: [] | [string];
    message: string;
    deviceId: [] | [string];
}): {
    id: string;
    status: ContactStatus;
    name: string;
    submittedAt: bigint;
    email: string;
    senderBlocked: boolean;
    senderPrincipal?: string;
    message: string;
    deviceId?: string;
} {
    return {
        id: value.id,
        status: from_candid_ContactStatus_n25(_uploadFile, _downloadFile, value.status),
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        senderBlocked: value.senderBlocked,
        senderPrincipal: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.senderPrincipal)),
        message: value.message,
        deviceId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.deviceId))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ownerName: string;
    ownerPrincipal: Principal;
    name: string;
    createdAt: bigint;
    parentFolderId: [] | [string];
}): {
    id: string;
    ownerName: string;
    ownerPrincipal: Principal;
    name: string;
    createdAt: bigint;
    parentFolderId?: string;
} {
    return {
        id: value.id,
        ownerName: value.ownerName,
        ownerPrincipal: value.ownerPrincipal,
        name: value.name,
        createdAt: value.createdAt,
        parentFolderId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.parentFolderId))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n7(_uploadFile, _downloadFile, value.role),
        profile: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
}): {
    principal: Principal;
    role: UserRole;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n7(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DocumentRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DocumentRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DocumentRecord_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newyear: null;
} | {
    none: null;
} | {
    easter: null;
} | {
    midsommar: null;
} | {
    christmas: null;
}): Holiday {
    return "newyear" in value ? Holiday.newyear : "none" in value ? Holiday.none : "easter" in value ? Holiday.easter : "midsommar" in value ? Holiday.midsommar : "christmas" in value ? Holiday.christmas : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<string>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        data: Uint8Array;
        mimeType: string;
        fileName: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        data: Uint8Array;
        mimeType: string;
        fileName: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserAccessLogEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserAccessLogEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ContactMessage>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ContactMessage>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n22(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    notactive: null;
}): ContactStatus {
    return "active" in value ? ContactStatus.active : "notactive" in value ? ContactStatus.notactive : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserListEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserListEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactMessage>): Array<ContactMessage> {
    return value.map((x)=>from_candid_ContactMessage_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentRecord>): Array<DocumentRecord> {
    return value.map((x)=>from_candid_DocumentRecord_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FolderRecord>): Array<FolderRecord> {
    return value.map((x)=>from_candid_FolderRecord_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserListEntry>): Array<UserListEntry> {
    return value.map((x)=>from_candid_UserListEntry_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAccessEntry>): Array<UserAccessEntry> {
    return value.map((x)=>from_candid_UserAccessEntry_n5(_uploadFile, _downloadFile, x));
}
function to_candid_ContactStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactStatus): _ContactStatus {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Holiday_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Holiday): _Holiday {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Holiday): {
    newyear: null;
} | {
    none: null;
} | {
    easter: null;
} | {
    midsommar: null;
} | {
    christmas: null;
} {
    return value == Holiday.newyear ? {
        newyear: null
    } : value == Holiday.none ? {
        none: null
    } : value == Holiday.easter ? {
        easter: null
    } : value == Holiday.midsommar ? {
        midsommar: null
    } : value == Holiday.christmas ? {
        christmas: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactStatus): {
    active: null;
} | {
    notactive: null;
} {
    return value == ContactStatus.active ? {
        active: null
    } : value == ContactStatus.notactive ? {
        notactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
