/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}

export type UserRole = { admin: null } | { user: null } | { guest: null };
export type Holiday = { none: null } | { easter: null } | { christmas: null } | { newyear: null } | { midsommar: null };
export type HolidayKey = "none" | "easter" | "christmas" | "newyear" | "midsommar";

export interface UserProfile {
    name: string;
    email: string;
    phone: string;
    registeredAt: bigint;
}

export interface UserAccessEntry {
    principal: Principal;
    role: UserRole;
}

export interface UserListEntry {
    principal: Principal;
    role: UserRole;
    profile: Option<UserProfile>;
}

export type CallResult = { ok: null } | { err: string };
export type ListUsersResult = { ok: UserListEntry[] } | { err: string };

export interface backendInterface {
    getMyRole(): Promise<UserRole>;
    getMyProfile(): Promise<Option<UserProfile>>;
    updateMyProfile(name: string, email: string, phone: string): Promise<CallResult>;
    listUsers(): Promise<ListUsersResult>;
    addUser(principalText: string, role: UserRole): Promise<CallResult>;
    updateUserRole(principalText: string, newRole: UserRole): Promise<CallResult>;
    removeUser(principalText: string): Promise<CallResult>;
    blockUser(principalText: string): Promise<CallResult>;
    updateUserProfile(principalText: string, name: string, email: string, phone: string): Promise<CallResult>;
    getActiveHoliday(): Promise<Holiday>;
    setActiveHoliday(holiday: Holiday): Promise<CallResult>;
    admin_addUserAccess(principalText: string, role: UserRole): Promise<void>;
    admin_updateUserAccess(principalText: string, role: UserRole): Promise<void>;
    admin_getUserAccess(): Promise<UserAccessEntry[]>;
}

export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    async getMyRole(): Promise<UserRole> {
        try {
            const result = await this.actor.getMyRole();
            const r = result as { admin?: null } | { user?: null } | { guest?: null };
            if ('admin' in r) return { admin: null };
            if ('user' in r) return { user: null };
            return { guest: null };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async getMyProfile(): Promise<Option<UserProfile>> {
        try {
            const result = await this.actor.getMyProfile();
            const arr = result as (UserProfile | null)[] | null;
            if (!arr || arr.length === 0 || arr[0] == null) return none();
            return some(arr[0] as UserProfile);
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async updateMyProfile(name: string, email: string, phone: string): Promise<CallResult> {
        try {
            const result = await this.actor.updateMyProfile(name, email, phone);
            const r = result as { ok?: null; err?: string };
            if ('ok' in r) return { ok: null };
            return { err: (r as any).err as string };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async listUsers(): Promise<ListUsersResult> {
        try {
            const result = await this.actor.listUsers() as any;
            if ('err' in result) {
                return { err: result.err as string };
            }
            const entries = (result.ok as any[]).map((entry: any) => ({
                principal: entry.principal,
                role: this._mapRole(entry.role),
                profile: entry.profile && entry.profile.length > 0 && entry.profile[0] != null
                    ? some(entry.profile[0] as UserProfile)
                    : none(),
            }));
            return { ok: entries };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async addUser(principalText: string, role: UserRole): Promise<CallResult> {
        try {
            const candidRole = this._toCandidRole(role);
            const result = await this.actor.addUser(principalText, candidRole) as any;
            if ('ok' in result) return { ok: null };
            return { err: result.err as string };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async updateUserRole(principalText: string, newRole: UserRole): Promise<CallResult> {
        try {
            const candidRole = this._toCandidRole(newRole);
            const result = await this.actor.updateUserRole(principalText, candidRole) as any;
            if ('ok' in result) return { ok: null };
            return { err: result.err as string };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async removeUser(principalText: string): Promise<CallResult> {
        try {
            const result = await this.actor.removeUser(principalText) as any;
            if ('ok' in result) return { ok: null };
            return { err: result.err as string };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async blockUser(principalText: string): Promise<CallResult> {
        try {
            const result = await this.actor.blockUser(principalText) as any;
            if ('ok' in result) return { ok: null };
            return { err: result.err as string };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async updateUserProfile(principalText: string, name: string, email: string, phone: string): Promise<CallResult> {
        try {
            const result = await this.actor.updateUserProfile(principalText, name, email, phone) as any;
            if ('ok' in result) return { ok: null };
            return { err: result.err as string };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async getActiveHoliday(): Promise<Holiday> {
        try {
            const result = await this.actor.getActiveHoliday() as any;
            return this._mapHoliday(result);
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async setActiveHoliday(holiday: Holiday): Promise<CallResult> {
        try {
            const candidHoliday = this._toCandidHoliday(holiday);
            const result = await this.actor.setActiveHoliday(candidHoliday) as any;
            if ('ok' in result) return { ok: null };
            return { err: result.err as string };
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async admin_addUserAccess(principalText: string, role: UserRole): Promise<void> {
        try {
            await this.actor.admin_addUserAccess(principalText, this._toCandidRole(role));
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async admin_updateUserAccess(principalText: string, role: UserRole): Promise<void> {
        try {
            await this.actor.admin_updateUserAccess(principalText, this._toCandidRole(role));
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    async admin_getUserAccess(): Promise<UserAccessEntry[]> {
        try {
            const result = await this.actor.admin_getUserAccess() as any[];
            return result.map((entry: any) => ({
                principal: entry.principal,
                role: this._mapRole(entry.role),
            }));
        } catch(e) { if (this.processError) return this.processError(e); throw e; }
    }

    private _mapRole(r: any): UserRole {
        if ('admin' in r) return { admin: null };
        if ('user' in r) return { user: null };
        return { guest: null };
    }

    private _toCandidRole(role: UserRole): any {
        if ('admin' in role) return { admin: null };
        if ('user' in role) return { user: null };
        return { guest: null };
    }

    private _mapHoliday(r: any): Holiday {
        if ('easter' in r) return { easter: null };
        if ('christmas' in r) return { christmas: null };
        if ('newyear' in r) return { newyear: null };
        if ('midsommar' in r) return { midsommar: null };
        return { none: null };
    }

    private _toCandidHoliday(holiday: Holiday): any {
        if ('easter' in holiday) return { easter: null };
        if ('christmas' in holiday) return { christmas: null };
        if ('newyear' in holiday) return { newyear: null };
        if ('midsommar' in holiday) return { midsommar: null };
        return { none: null };
    }
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
